#file: noinspection HttpUrlsUsage
server:
  port: 8761

eureka:
  instance:
    # IMPORTANTE: Dentro de Docker, preferimos usar el nombre del servicio dentro del docker-compose (ej: 'discovery') en lugar de 'localhost' o 'discovery-server'
    hostname: discovery-server
    prefer-ip-address: true # En Docker, es mejor usar la dirección IP interna para evitar problemas de resolución de nombres entre contenedores
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # Se transforma en http://discovery:8761/eureka/
  server:
    enable-self-preservation: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

logging:
  level:
    com.netflix: DEBUG
    org.springframework.cloud: DEBUG